### ISSUE TITLE
Does not build with Cordova Android 6.4.0

### ISSUE THREAD

**Issue by M2UNO3** [NeutrinosPlatform/cordova-plugin-mobile-ocr#3]
BUILD FAILED in 40s
(node:15804) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: cmd: Command failed with exit code 1 Error output:
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
\cordova\platforms\android\src\com\neutrinos\ocrplugin\Textocr.java:89: error: cannot find symbol
bitmap = MediaStore.Images.Media.getBitmap(cordova.getContext().getContentResolver(), uri);
^
symbol: method getContext()
location: variable cordova of type CordovaInterface
\cordova\platforms\android\src\com\neutrinos\ocrplugin\Textocr.java:93: error: cannot find symbol
bitmap = decodeBitmapUri(cordova.getContext(), uri);
^
symbol: method getContext()
location: variable cordova of type CordovaInterface
l\cordova\platforms\android\src\com\neutrinos\ocrplugin\Textocr.java:133: error: cannot find symbol
detector = new TextRecognizer.Builder(cordova.getContext()).build();
^
symbol: method getContext()
location: variable cordova of type CordovaInterface

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

**Comment by ChrisTomAlx** [comment]
Thank you for raising this issue. Tested it and can confirm the **build is failing** in cordova android 6.4.0. However it does work for cordova android 7.0.0+. Just tested it again to confirm. 

I am working on this issue. Will let you know once a fix is available.

Cheers,
[Chris](https://github.com/ChrisTomAlx)
[Neutrinos](http://www.neutrinos.co/)

**Comment by ChrisTomAlx** [comment]
This issue has been fixed and tested. Cordova android 6.4.0 builds are successfully running. Let me know if you run into any more trouble. Closing this issue for now.
Have a nice day. 

Cheers,
[Chris](https://github.com/ChrisTomAlx)
[Neutrinos](http://www.neutrinos.co/)

**Comment by M2UNO3** [comment]
Thank you for fixing it @ChrisTomAlx !
